export { Homepage } from './Homepage'
export { HomepageAbout } from './HomepageAbout'
export { HomepageContact } from './HomepageContact'
export { HomepageFAQ } from './HomepageFAQ'
export { HomepageNav } from './HomepageNav'
export { HomepageServices } from'./HomepageServices'